# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - closed
    branches: [ "main" ]
  workflow_dispatch:

env:
  SHA: ${{ github.sha }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup TAG env
        run: |
          echo "TAG=$(date '+%Y%m%d%H%M%S')-${SHA:0:7}" >> "$GITHUB_ENV"

      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.TAG }}" # This will output 'yellow'

